import Head from "next/head";
import style from "../styles/Home.module.css";

import { Header } from "../components/partials/Header";
import { Footer } from "../components/partials/Footer";
import { Form } from "../components/partials/Form";
import { Section } from "../components/Section";

export default function Contato() {
  return (
    <div className={style.container}>
      <Head>
        <title>VtrsgDEV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/avatar.jpg" />
      </Head>
      <Header />
      <main className={style.main}>
        <Section label="Contato">
          <Form />
        </Section>
      </main>
      <Footer />
    </div>
  );
}
