import Head from "next/head";
import style from "../styles/Home.module.css";

import { Header } from "../components/partials/Header";
import { Footer } from "../components/partials/Footer";

export default function Contato() {
  return (
    <div className={style.container}>
      <Head>
        <title>VtrsgDEV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/avatar.jpg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https: //fonts.googleapis.com/css2?family= Courier+Prime:wght@700 & family = Montserrat:wght@400;500;700 & family= Roboto+Mono:wght@700 & family= Roboto:wght@400; 700 & display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Header />
      <main className={style.main}></main>
      <Footer />
    </div>
  );
}
