import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Header } from '../components/Header'
import { Initial } from '../components/InitialSection'
import { About } from '../components/AboutSection'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>VtrsgDEV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https: //fonts.googleapis.com/css2?family= Courier+Prime:wght@700 & family = Montserrat:wght@400;500;700 & family= Roboto+Mono:wght@700 & family= Roboto:wght@400; 700 & display=swap" rel="stylesheet"></link>
      </Head>
      <Header/>
      <main className={styles.main}>
        <Initial/>
        <About/>
      </main>
    </div>
  )
}
