import Head from "next/head";
import style from "../styles/Home.module.css";

import { Header } from "../components/partials/Header";
import { GridTools } from "../components/partials/GridTools";
import { GridSkills } from "../components/partials/GridSkills";
import { Footer } from "../components/partials/Footer";


import { Initial } from "../components/InitialSection";
import { Section } from "../components/Section";
import { About } from "../components/AboutSection";

export default function Home() {
  return (
    <div className={style.container}>
      <Head>
        <title>VtrsgDEV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/avatar.jpg" />      
      </Head>
      <Header />
      <main className={style.main}>
        <Initial />
        <About />
        <Section label={"Ferramentas"}>
          <GridTools/>
        </Section>
        <Section label={"Habilidades"}>
          <GridSkills/>
        </Section>
      </main>
      <Footer/>
    </div>
  );
}
